config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'

  resource :free_time, only: [:edit, :update]

  resources :buttons

  devise_for :users
  
  resources :users, only: [:show, :index, :destroy] do 
    resource :summary, only: [:show, :destroy]
  end
  

end

app/models/free_time.rb
class FreeTime < ActiveRecord::Base
  belongs_to :user
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :free_time, dependent: :destroy
  has_many :work_relax_buttons, dependent: :destroy
  has_many :records, dependent: :destroy
end

app/models/work_relax_button.rb
class WorkRelaxButton < ActiveRecord::Base
  belongs_to :user
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    current_user
  end

end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController
  def new
    @user = current_user
    # Redirect user to home path if not logged in
    if !current_user
      redirect_to root_path
    end
  end

  def create
    params[:buttons][:work_relax] = params[:buttons][:work_relax] === "true" ? true : false
    
     @button = WorkRelaxButton.create(is_work: params[:buttons][:work_relax], description: params[:buttons][:description],
      user_id: current_user.id)
    if @button.errors.any?
      render(new_button_path) and return
    end
    redirect_to buttons_path
  end


  def index
    if !current_user
      redirect_to root_path
    else 
      @buttons = current_user.work_relax_buttons
    end
  end

  def edit
    if !current_user
      redirect_to root_path
    else 
      @button = WorkRelaxButton.find(params[:id])
    end 
  end

  def update 
    params[:buttons][:work_relax] = params[:buttons][:work_relax] === "true" ? true : false
    
    button = WorkRelaxButton.find(params[:id])
    button.update(is_work: params[:buttons][:work_relax], description: params[:buttons][:description])
    if button.errors.any?
      @button1 = button
      @button = WorkRelaxButton.find(params[:id])
      render "edit" and return
    end
    redirect_to buttons_path
  end

  def destroy
    params[:delete].each do |id|
      WorkRelaxButton.find(id[0].to_i).destroy
    end
    redirect_to buttons_path
  end
end

app/controllers/free_times_controller.rb
class FreeTimesController < ApplicationController

  def edit 

  end

  def update 
    new_free_time = Integer(params[:free_time][:free_time])
    user = User.find(FreeTime.find(params[:id]).user_id)
    user.free_time.update(free_time: new_free_time)
    redirect_to users_path

  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def save
  end

  def help
  end

  def about 
  end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
 include SummariesHelper

  def show
    @work_records = current_user.records.where("is_work = ?", true)
    @relax_records = current_user.records.where("is_work = ?", false)
    @records = current_user.records
    @totalWork = 0
    @totalRelax = 0 

    @records.each do |record|
      time_spent = record.time_spent  
      record.is_work ? @totalWork += time_spent : @totalRelax += time_spent
    end

    @work_graph = pie_chart(@work_records, "Work Activity", "1D804E")
    @relax_graph = pie_chart(@relax_records, "Relax Activity", "5D9BBA")
    
  end

  def destroy
    Record.find(params[:record_id]).delete
    redirect_to user_summary_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

    if current_user.try(:admin?)
      @users = User.all
    else 
      redirect_to root_path
    end  
  end

  def destroy
    User.find(params[:id]).delete
    redirect_to users_path

  end

  def show 
    @user = User.find(params[:id])

    # Update the free time and saves a record of the activity
    if current_user && request.get? && params.has_key?(:ftime)
      current_user.free_time.update(free_time: params[:ftime].to_i)

      params[:is_work] = params[:is_work] === "true" ? true : false

      record = current_user.records.create(is_work: params[:is_work], description: params[:description], 
        time_spent: params[:stime])

      params.each do |key, value| 
        params.delete key
      end

    end

    if current_user

      # Check if new user
      if current_user.free_time_id.blank? 

        # Initial values for new user
        initial_free = 0
        initial_work_button = "This is a Work Button. Starting the timer when this is selected with increase your free time" 
        initial_relax_button = "This is Relax Button. Starting the timer when this is selected will decrease your free time"
        edit_work_button = "You can edit these buttons, add your own button, or delete these buttons by clicking 'Add/edit buttons'"
        summary_relax_button = "You can view your activity log by clicking the 'Summary' link in the navigation bar"

        # Creates the Free Time item associated with the user
        free = FreeTime.create(free_time: initial_free, user_id: current_user.id)
        current_user.update(free_time_id: free.id)

        # Create initial work buttons
        current_user.work_relax_buttons.create(is_work: true, description: initial_work_button)
        current_user.work_relax_buttons.create(is_work: false, description: initial_relax_button)



      end

      @freeTime = current_user.free_time.free_time # assign the free time to be used by the view
      @buttons = current_user.work_relax_buttons
      
      # assign variables to be used by javascript
      gon.freeTime = @freeTime
      gon.user = @user
    else 
      redirect_to new_user_session_path
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title= "Work To Relax"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/buttons_helper.rb
module ButtonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  
  def update_free_time
    
  end
end

app/helpers/summaries_helper.rb
module SummariesHelper

  def total_time(total)
    base_string = "#{total} seconds"
    if total >= 60
      total_min = total / 60
      total_sec = total - (total_min * 60)

      return total_min > 1 ?  "#{total_min} minutes #{total_sec} seconds" : "#{total_min} minute #{total_sec} seconds"
    else 
      base_string
    end
  end

  def pie_chart(records, title, color)
    records_hash = {}
    total_time = 0
    records.each do |record| 
      time_spent = record.time_spent
      records_hash[record.description] ||= 0
      records_hash[record.description] += time_spent
      total_time += time_spent
    end

    data = records_hash.collect { |description, time_spent| time_spent }
    labels = records_hash.collect { |description, time_spent| "#{description} (#{(100.0 *time_spent/total_time).round}%)"}

    Gchart.pie(
      title: title,
      data: data,
      labels: labels,
      bar_colors: color,
      size: '695x380'
      ) 
  end

end

app/views/buttons/edit.html.erb
<% provide(:title, "Edit Button") %>

<h2>Update Button</h2>
<%= content_tag :p, "Description can't be blank", class: "alert alert-danger" if !@button1.blank? %>
<p> Edit: "<%= @button.description %>" Button  </p>

<hr/>

<%= form_for(:buttons, url: button_path(button_id: params[:id]), method: :patch) do |f| %>

  <div class="form-group">
    <%= f.select :work_relax, options_for_select([["Work", true, {class: 'work-option'}], ["Relax", false, {class: 'relax-option'}]], @button.is_work), {selected: "Relax"}, {class: 'form-control input-small'} %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_field :description, value: @button.description, class: 'form-control' %>
  </div>

  <hr/>

  <%= f.submit "Update Button", class: 'btn btn-success' %>

<% end %>

<%= link_to "Back to buttons", buttons_path %>

app/views/buttons/index.html.erb
<% provide(:title, "Buttons") %>
<% user = current_user %>
<div class="container"> 

  <%= form_tag button_path(id: 1), method: :delete do %>
    <h3 class="work-button-label" >Work Buttons</h3>

    <ul style="list-style:none">
      <% @buttons.each do |i| %>
        <% if i.is_work %>
          <li>
            <%= check_box_tag "delete[#{i.id}]", i.description %> <%= i.description %> 
            <%= link_to "Edit", edit_button_path(:id => i.id), method: :get %>
          </li>
        <% end %>
      <% end %>
    </ul>

    <hr/>

    <h3 class="relax-button-label">Relax Buttons</h3>
    <ul style="list-style:none">
      <% @buttons.each do |i| %>
        <% if !i.is_work %>
          <li> 
            <%= check_box_tag "delete[#{i.id}]", i.description %> <%= i.description %> 
            <%= link_to "Edit", edit_button_path(:id => i.id), method: :get %>
          </li>

        <% end %>
      <% end %>
    </ul>

    <hr/>
    <%= link_to "Add New Button", new_button_path, class: 'btn btn-info' %>
    <%= submit_tag "Delete Selected", class: "btn btn-danger" %>
  <% end %>
  <p style="margin-top: 10px"><%= link_to "Back to Timer", user_path(id: user.id) %></p>
</div>

app/views/buttons/new.html.erb
<h2>Create a Button</h2>

<hr/>
<%= content_tag :p, "Description can't be blank", class: "alert alert-danger" if @button%>
<%= form_for(:buttons, url: buttons_path, method: :post) do |f| %>

  <div class="form-group">
    <%= f.select :work_relax, [["Work", true], ["Relax", false]], {}, {class: "form-control input-small"} %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <hr/>

  <%= f.submit "Create New Button", class: 'btn btn-success' %>

<% end %>

<%= link_to "Back to buttons", buttons_path %>

app/views/free_times/edit.html.erb
<h2>Free Time Edit Page</h2>

<p> Update Free Time for "<%= User.find(FreeTime.find(params[:id]).user_id).email %>"</p> 

<%= form_for :free_time, url: free_time_path(id: params[:id]), method: :patch do |f| %>

  <%= f.label :Free_Time %>
  <%= f.text_field :free_time %>

  <%= f.submit "Update Free Time", class: "btn btn-primary" %>

<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "Work To Relax", root_path, id: "logo" %>
    <nav>
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <% user = current_user %>
          <div id="nav-buttons" class="nav navbar-nav navbar-right">

            <% if current_user %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary navbar-btn" %>
            <% else %>
              <%= link_to 'Log in', new_user_session_path, class: "btn btn-primary navbar-btn" %>
              <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success navbar-btn" %>
            <% end %>

          </div>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "How to Use", help_path %></li>
              <% if current_user %>
                <li><%= link_to "Timer", user_path(id: user.id) %></li>
             
                <li><%= link_to "Summary", user_summary_path(user_id: user.id), method: :get%></li>
                <% if current_user.try(:admin?) %>
                  <li><%= link_to "All users", users_path %></li>
                <% end %>
                <li ><%= link_to current_user.email, "#", id: "logged-in-user" %></li>
              <% end %>
            
   
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %></title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/layouts/main_page.html.erb
<h2>Timer</h2>

<div class="container text-center">
  <p id="counter"></p>
  <button id="start-button" type="button" class="btn btn-success">Start</button>
  <button id="stop-button" type="button" class="btn btn-danger">Stop</button>
  <button id="reset-button" type="button" class="btn btn-primary">Reset</button>
</div>

<h2>Time stored</h2>
<p> Free Time: <span id="free"></span></p>


<h2>Buttons</h2>

<div class="container">
  <button class="btn btn-success" onclick="toggle()">
    Work 
  </button>
  <input id="work-toggle" data-toggle="toggle" checked type="checkbox">
  
</br>

  <button class="btn btn-warning" onclick="toggle()">
    Free 
  </button>
  <input id="free-toggle" data-toggle="toggle" type="checkbox">
  
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "How To Use") %>
<h1 style="margin-botton: 10px">How to use <span class="title">Work To Relax</span></h1>

<hr/>

<ol>
  <li> Sign up for an account. </li>

  <li> After signing up, you will be redirected to the timer. Notice on the timer page how you have 0 Free Time. You can't relax yet, so go ahead and start working to earn free time! </li>

  <li> Press "start" to start the timer, and reset to save the data. If the timer is already started and you switch your activity, it will automatically reset the timer and save the data.</li>

  <li> You can add, edit, or delete buttons by clicking the "Add/Edit Button". </li>

  <li> Click on the Summary button to view your activity log (if the timer is running, make sure you save the data first). You can delete individual entries if you no longer want to keep track of it.</li>

</ol>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<h1> Welcome to <span class="title">Work to Relax</span>! </h1>

<hr/>
<h3>To get started, click <%= link_to "this link", help_path %>. </h3>

<hr/>
<div>
  <a class="btn btn-primary" data-toggle="collapse" href="#home-text" aria-expanded="false" aria-controls="home-text">About the Website</a>
  <div id="home-text" class="home-div collapse well" data-toggle="collapse">
    <p>This website is designed to help procrastinators. </p>

    <p>Being a former procrastinator, I noticed that there was a common theme with procrastination: When I didn't want to study or do any work, I did something else instead. But when I procrastinated, I couldn't fully enjoy what I was doing, since I knew there were things that needed to get done. "Work To Relax" helps address this problem. </p>

    <p>The concept is pretty simple. For every minute of work you do, you get a minute of "free time". The free time accumulated can then be used to relax in whichever way you want to. This allows you to relax without guilt, since you earned the free time through working.

    <p>In addition to keeping track of the free time you have, this website also keeps track of the activities you do, so you can analyze the data and gain a sense of how you are spending your time.</p>

    <p> I hope you enjoy the website that I created!</p>

    <p>Tony </p>
  </div>
</div>

<hr/>

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<p class="caption"> Earn free time through doing working! Use the timer to keep track of your progress</p>
			<%= image_tag "timer_sample.png" %>
		</div>
		<div class="col-md-6">
			<p class="caption">Keep track of what you are doing, and when you did it</p>
			<%= image_tag "work_summary_sample.png" %>
		</div>
	</div>

	<hr/>

	<div class="row">
		<div class="col-md-6">
			<p class="caption">See what proportion of work activities you did</p>
			<%= image_tag "work_chart_sample.png" %>
		</div>

		<div class="col-md-6">
			<p class="caption">See what proportion of relax activities you did</p>
			<%= image_tag "relax_chart_sample.png" %>
		</div>
	</div>

</div>

app/views/summaries/show.html.erb
<% provide(:title, "Summary") %>
<% user = current_user %>
<h1 style="display: inline; margin-right: 10px">Summary</h1>  <%= link_to "Back to timer", user_path(id: user.id) %>
<hr/>
<% user = current_user %>

<h3>Work Summary</h3>

<% if !@work_records.blank? %>
 
  <div>
      <a href="#work-graph" data-toggle="collapse" aria-expanded="false" aria-controls="work-graph"> Show/Hide Graph</a>
      <div id="work-graph" class="collapse in" data-toggle="collapse">
        <%= image_tag @work_graph %>
      </div>
  </div>
  <p id="total-work">Total Work: <%= total_time(@totalWork) %> </p>
<% end %>

<div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Description</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Time Spent</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @work_records.each do |record| %>
        <% time_spent = record.time_spent %>
        <tr>
          <td> <%= record.description %> </td>
          <td> <%= (record.created_at).in_time_zone("EST").strftime("%D, %r") %> </td>
          <td> <%= (record.created_at + time_spent).in_time_zone("EST").strftime("%D, %r") %> </td>
          <td> <%= total_time(time_spent) %> </td>
          <td> <%= link_to "Delete", user_summary_path(user_id: user.id, record_id: record.id), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<hr/>
<h3>Relax Summary</h3>

<% if !@relax_records.blank? %>
  <div>
    <a href="#relax-graph" data-toggle="collapse" aria-expanded="false" aria-controls="relax-graph"> Show/Hide Graph</a>
    <div id="relax-graph" class="collapse in" data-toggle="collapse">
      <%= image_tag @relax_graph %>
    </div>
  </div>
  <p id="total-relax">Total Relax: <%= total_time(@totalRelax) %> </p>
<% end %>

<div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Description</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Time Spent</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @relax_records.each do |record| %>
        <% time_spent = record.time_spent %>
        <tr>
          <td> <%= record.description %> </td>
          <td> <%= (record.created_at).in_time_zone("EST").strftime("%D, %r") %> </td>
          <td> <%= (record.created_at + time_spent).in_time_zone("EST").strftime("%D, %r") %> </td>
          <td> <%= total_time(time_spent) %> </td>
          <td> <%= link_to "Delete", user_summary_path(user_id: user.id, record_id: record.id), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p><%= link_to "Back to Timer", user_path(id: user.id), class: "btn btn-default" %></p>
</div>

app/views/users/index.html.erb
<h2>Show all user page</h2>

 
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>User Id</th>
        <th>User email</th>
        <th> Free Time</th>
        <th>Delete?</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <% if !(user.admin?) %>
          <td> <%= user.id %></td>
          <td> <%= user.email %></td>
          <td> <%= user.free_time.free_time %> <%= link_to "Edit", edit_free_time_path(id: user.free_time.id) %></td>
          <td> <%= link_to "Delete", user_path(id: user.id), method: :delete %></td>

        </tr>
        <% end %>
      <% end %>
    </tbody>
  

  </table>

app/views/users/show.html.erb
<% provide(:title, "Timer") %>
<% user = current_user %>
<div class="container">
  <div id="instructions" class=" collapse" data-toggle="collapse">
    <ol>
      <li> Press "start" to start the timer, and reset to save the data. If the timer is already started and you switch your activity, it will automatically reset the timer and save the data.</li>

      <li> You can add, edit, or delete buttons by clicking the "Add/Edit Button". </li>

      <li> Click on the Summary button to view your activity log (if the timer is running, make sure you save the data first). You can delete individual entries if you no longer want to keep track of it.</li>

    </ol>
  </div>
  <p id="notice" class="alert alert-success"></p>

  <div class="text-center">
    <a href="#instructions" data-toggle="collapse" aria-expanded="false" aria-controls="instructions">  Show/Hide Instructions</a>
    <p id="counter" class="counter-pause"></p>
    <button id="start-button" type="button" class="btn btn-success">Start</button>
    <button id="reset-button" type="button" class="btn btn-primary">Reset/Save</button>
    <%= link_to "Summary", user_summary_path(user_id: user.id), class: "btn btn-info", id: "summary-button" %>
  </div>
  <hr/>
  <div class="text-center">
    <h3>Free Time Stored:</h3>
    <div><span id="free"></span> </div>
  </div>
  <hr/>
    <div class="row">
      <div class="col-md-6">
          <h3 class="text-center work-label"> Work </h3>
          <div class="work-buttons text-center">
            <!-- Create all the work radio buttons --> 
            <% if current_user %>
              <% @buttons.each do |i| %>
                <% if i.is_work %>
                  <p class="activity"><%= radio_button_tag 'work-relax', 'work', true, class: i.description %> <%= i.description %></p>
                <% end %> 
              <% end %>
            <% end %>
          </div>
      </div>
      <div class="col-md-6 border-left">
        <h3 class="text-center relax-label"> Relax </h3>
        <div class="relax-buttons text-center">
           <!-- Create all the relax radio buttons -->
          <% if current_user %>
            <% @buttons.each do |i| %>
              <% if !i.is_work %>
                <p class="activity"><%= radio_button_tag 'work-relax', 'relax', false, class: i.description %> <%= i.description %> </p>
              <% end %> 
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  <hr/>


    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= link_to "Add/Edit Buttons", buttons_path, class: 'btn btn-warning btn-block' %>
      </div>
    </div>

</div>